services:
  - type: web
    name: gestion-affaires-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL_REQUIRE
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: TIME_ZONE
        value: "Africa/Lome"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
