# Generated by Django 5.0.14 on 2026-09-07 22:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_pdv', models.CharField(choices=[('DEPOT', 'Dépôt'), ('BAR', 'Bar'), ('RESTAURANT', 'Restaurant')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('unite', models.CharField(help_text='Unité de vente : carton, casier, bouteille, litre...', max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, help_text='Renseignée au départ du commercial ; les soldes restent consultables.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('solde_marchandise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('solde_financier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial', to=settings.AUTH_USER_MODEL)),
                ('point_de_vente', models.ForeignKey(help_text='Dépôt de rattachement, utilisé pour la tarification.', on_delete=django.db.models.deletion.PROTECT, related_name='commerciaux', to='core.pointdevente')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('solde_marchandise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('solde_financier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.commercial')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moyen_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('date_encaissement', models.DateTimeField(help_text='Horodatage de la saisie terrain, pas de la synchronisation.')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaissements', to='core.client')),
                ('collecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaissements_collectes', to='core.commercial')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaissements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
                'ordering': ['-date_encaissement'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('type', models.CharField(choices=[('ENTREE_DEPOT', 'Entrée en dépôt (achat/réception)'), ('AFFECTATION_COMMERCIAL', 'Affectation à un commercial'), ('DEPOT_CLIENT', 'Dépôt chez un client'), ('VENTE_DECLAREE', 'Vente déclarée par un client'), ('RETOUR_CLIENT', 'Retour du client vers le commercial'), ('RETOUR_DEPOT', 'Retour du commercial vers le dépôt'), ('VENTE_DIRECTE', 'Vente directe en point de vente'), ('PERTE', 'Perte / casse')], max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text="Tarif en vigueur au moment du mouvement, figé pour l'historique.", max_digits=10, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text="quantite x prix_unitaire, figé pour l'historique.", max_digits=12, null=True)),
                ('date_mouvement', models.DateTimeField(help_text='Horodatage de la saisie terrain, pas de la synchronisation.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Capturée au moment de la saisie, notamment pour un dépôt.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mouvements/%Y/%m/')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.commercial')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock_crees', to=settings.AUTH_USER_MODEL)),
                ('point_de_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.pointdevente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_effet', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='core.pointdevente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='core.produit')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['-date_effet'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.UniqueConstraint(fields=('produit', 'point_de_vente', 'date_effet'), name='tarif_unique_produit_pdv_date'),
        ),
    ]
