# Generated by Django 5.0.14 on 2026-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='La Nativité', max_length=200)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XOF', max_length=3)),
                ('mdp_longueur_min', models.PositiveSmallIntegerField(default=8)),
                ('mdp_exiger_majuscule', models.BooleanField(default=True)),
                ('mdp_exiger_chiffre', models.BooleanField(default=True)),
                ('mdp_exiger_caractere_special', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprise',
            },
        ),
    ]
