# Generated by Django 5.0.14 on 2026-09-10 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entreprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(blank=True, max_length=30)),
                ('nombre_personnes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_reservation', models.DateTimeField(help_text='Date et heure prévues de la réservation.')),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('HONOREE', 'Honorée')], default='CONFIRMEE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_creees', to=settings.AUTH_USER_MODEL)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.pointdevente')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_reservation'],
            },
        ),
    ]
