# Generated by Django 5.0.14 on 2026-09-10 14:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_evenement',
            field=models.CharField(blank=True, help_text='Ex : anniversaire, mariage, baptême... Libre, pas de liste fermée.', max_length=100),
        ),
        migrations.CreateModel(
            name='StockPointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.pointdevente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.produit')),
            ],
            options={
                'verbose_name': 'Stock point de vente',
                'verbose_name_plural': 'Stocks points de vente',
                'ordering': ['point_de_vente__nom', 'produit__nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockpointdevente',
            constraint=models.UniqueConstraint(fields=('point_de_vente', 'produit'), name='stock_unique_pdv_produit'),
        ),
    ]
