# Generated by Django 5.0.14 on 2026-09-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_type_evenement_stockpointdevente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mode_vente',
            field=models.CharField(choices=[('DEPOT_VENTE', 'Dépôt-vente'), ('CASH', 'Cash')], default='DEPOT_VENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(blank=True, help_text='Obligatoire en dépôt-vente ; sans objet pour un client cash.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.commercial'),
        ),
    ]
