# Generated by Django 5.0.14 on 2026-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_mode_vente_alter_client_commercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='solde_financier',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='solde_marchandise',
        ),
        migrations.AlterField(
            model_name='commercial',
            name='date_sortie',
            field=models.DateField(blank=True, help_text="Renseignée au départ du commercial ; les marchands qu'il a tagués restent consultables.", null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('ENTREE_DEPOT', 'Entrée en dépôt (achat/réception)'), ('DEPOT_CLIENT', 'Dépôt chez un marchand'), ('VENTE_DECLAREE', 'Vente déclarée par un marchand'), ('RETOUR_CLIENT', 'Retour du marchand vers le dépôt'), ('VENTE_DIRECTE', 'Vente directe en point de vente'), ('PERTE', 'Perte / casse')], max_length=30),
        ),
    ]
