# Generated by Django 5.0.14 on 2026-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_commercial_solde_financier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='role',
            field=models.CharField(choices=[('PDG', 'PDG'), ('GERANT', 'Gérant'), ('CHARGE_VENTES', 'Chargé(e) des ventes'), ('COMPTABLE', 'Comptable'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
