# Generated by Django 5.0.14 on 2026-09-11 16:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commercial_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissement',
            name='monnaie_rendue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monnaie rendue au marchand sur le montant reçu.', max_digits=12),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant brut physiquement remis par le marchand, avant rendu de monnaie.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant net qui diminue le solde financier (montant_recu - monnaie_rendue).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
